package id.camelliaalfina.wisatajogja

object SeniData {
    private val seniNames = arrayOf(
        "Jazz Mben Senen",
        "Keraton Yogyakarta",
        "Jemparingan",
        "Museum Affandi",
        "Tari Ramayana",
        "Museum Sonobudoyo",
        "Wayang Kulit",
        "Pantai Drini",
        "Pantai Glagah",
        "Pantai Indrayanti",
        "Pantai Jogan",
        "Pantai Kesirat",
        "Pantai Krakal",
        "Pantai Nglambor",
        "Pantai Ngobaran",
        "Pantai Ngrenehan",
        "pantai Parangtritis",
        "Pantai Pok Tunggal",
        "Pantai Slili",
        "Pantai Wediombo",
        "Pantai Wohkudu",
        "Pantai Siung",
        "Candi Prambanan",
        "Candi Borobudur",
        "Candi Mendut",
        "Ratu Boko",
        "Candi Ijo",
        "Candi Plaosan",
        "Candi Kalasan",
        "Candi Pawon",
        "Candi Sambisari",
        "Candi Sari",
        "Candi Barong",
        "Candi Kimpulan"
    )
    private val seniDetails = arrayOf(
        "Jazz Mben Senen yang berarti jazz setiap Senin merupakan sebuah pertunjukan musik jazz yang rutin diselenggarakan setiap hari Senin malam oleh Komunitas Musik Jazz Jogja. Jazz Mben Senen yang berlokasi di halaman Bentara Budaya - Kota Baru ini menghadirkan sebuah pertunjukkan musik yang elegan namun merakyat. Untuk dapat menikmati jazz di Jazz Mben Senen kita tidak dikenai biaya selain parkir kendaraan, namun disediakan kotak sumbangan bagi para penonton jika ingin menyumbang seikhlasnya. Jazz Mben Senen dimulai dari pukul 20.00 hingga tengah malam. Suasana santai dan hangat dapat ditemukan di sini, di antara MC yang asik dan kocak, para musisi, serta pengunjung yang dapat berpartisipasi dalam bermain musik dengan adanya jam session. Ya, di sini kita bisa nge-jam bareng mengekspresikan kemampuan bermusik kita dengan kawan-kawan di Jazz Mben Senen, begitu pun bagi penikmat musik jazz untuk sekedar duduk santai menikmati permainan musik dari para musisi Jazz. Melepas lelah dari kesibukan hari pertama di awal minggu dengan menghabiskan malam sambil menikmati Jazz di tengah-tengah keramahan Jogja, tentu bisa jadi pilihan yang cocok untuk siapapun para pecinta musik!",
        "Keraton Yogyakarta tidak hanya menjadi tempat tinggal raja, namun juga menjadi penjaga nyala kebudayaan Jawa. Di tempat ini Anda dapat belajar dan melihat secara langsung bagaimana budaya tetap dilestarikan di tengah laju perkembangan dunia. Ada banyak hal yang bisa disaksikan di Keraton Yogyakarta, mulai dari aktivitas abdi dalem yang sedang melakukan tugasnya atau melihat koleksi barang-barang Keraton. Koleksi yang disimpan dalam kotak kaca yang tersebar di berbagai ruangan tersebut mulai dari keramik dan barang pecah belah, senjata, foto, miniatur dan replika, hingga aneka jenis batik beserta deorama proses pembuatannya. Selain itu, wisatawan juga bisa menikmati pertunjukan seni dengan jadwal berbeda-beda setiap harinya. Pertunjukan tersebut mulai dari macapat, wayang golek, wayang kulit, dan tari-tarian. Untuk menikmati pertunjukkan seni wisatawan tidak perlu mengeluarkan biaya tambahan. Jika datang pada hari selasa wage, Anda bisa menyaksikan lomba jemparingan atau panahan gaya Mataraman di Kemandhungan Kidul. Jemparingan ini dilaksanakan dalam rangka tinggalan dalem Sri Sultan HB X. Keunikan dari jemparingan ini adalah setiap peserta wajib mengenakan busana tradisional Jawa dan memanah dengan posisi duduk.",
        "Di kawasan Keraton Yogyakarta, seni memanah masih dilestarikan. Masyarakat menyebutnya dengan jemparingan. Gaya yang digunakan pun masih mengikuti gaya jemparingan Mataram asli ajaran dari Sri Sultan Hamengku Buwono I. Bagi para abdi dalem keraton, memanah bukan hanya sebagai olah raga, namun juga sebagai olah rasa. Beberapa waktu yang lalu, tim YogYes meminta izin pada pihak keraton yang diwakili oleh KRT Jatiningrat atau biasa dipanggil Romo Tirun (Romo adalah panggilan untuk laki-laki dewasa) untuk dapat mengikuti latihan rutin jemparingan para abdi dalem. Rasa senang menyeruak di dada kami karena beliau mengabulkan keinginan mengikuti latihan yang rutin dilakukan setiap Selasa itu. Tak lupa, Romo Tirun pun mengenalkan tentang jemparingan. Pukul 15.00 WIB, kami datang ke Kemandungan, utara Alun-Alun Selatan Yogyakarta. Baru ada tiga orang yang datang di sana. Kami pun menunggu hingga para abdi dalem datang. Sekitar pukul 15.30 WIB latihan jemparingan dimulai. Awalnya, kami hanya memperhatikan para abdi dalem menembakkan anak panah ke sasaran. Sasarannya menggunakan orang-orangan atau wong-wongan berbentuk silinder dengan panjang sekitar 35 cm dan diameter sekitar 3,5 cm. Wong-wongan ini dibagi menjadi tiga bagian, yaitu kepala dengan warna merah berpoin 3, leher berwarna kuning berpoin 2, dan badan berwarna putih berpoin 1. Di bawah wong-wongan terpasang bola yang melambangkan godaan atau gangguan dengan poin -1.",
        "Museum Affandi adalah kapsul semesta Affandi, Sang Grandmaster seni lukis kebanggaan Indonesia. Seluruh aspek kehidupannya terabadikan di sini. Dari awal sampai akhir karirnya sebagai pelukis kelas dunia, sampai hidup dan matinya sebagai manusia biasa. Sebagai salah satu pusat pariwisata Indonesia, Yogyakarta memiliki beberapa museum yang menarik untuk kita kunjungi. Ada museum kebudayaan Ullen Sentalu yang bangunannya duduk begitu indah dan asri di bawah lereng Merapi. Ada Museum Sonobudoyo, di salah satu sudut Alun-Alun Utara, yang menampung hampir 63 ribu koleksi dari berbagai macam kategori. Ada museum kekinian, seperti De Mata dan De Arca di XT Square, yang cocok untuk penggemar swafoto. Dari berbagai museum di atas, salah satu yang banyak menarik wisatawan adalah Museum Affandi. Di museum seluas 3.500 meter persegi ini, kita dapat melihat dan membayangkan kehidupan Affandi dan keluarganya semasa beliau hidup, sekaligus mencecap sekitar 300 karya dari 4000-an karya-karya lukis yang dihasilkan sepanjang karirnya yang terkenal itu. Singkatnya, museum Affandi menampung seluruh rentang dan sisi kehidupan Affandi Koesoema, baik sebagai seniman (as an artist) maupun sebagai manusia biasa (as a person).",
        "Visualisasi mengagumkan dari epos legendaris dalam kebudayaan Jawa, Ramayana. Dipentaskan di panggung terbuka, Sendratari Ramayana mengajak anda menikmati cerita dalam rangkaian gerak tari khas Jawa yang diiringi musik gamelan. Sendratari Ramayana adalah seni pertunjukan yang cantik, mengagumkan dan sulit tertandingi. Pertunjukan ini mampu menyatukan ragam kesenian Jawa berupa tari, drama dan musik dalam satu panggung dan satu momentum untuk menyuguhkan kisah Ramayana, epos legendaris karya Walmiki yang ditulis dalam bahasa Sanskerta. Kisah Ramayana yang dibawakan pada pertunjukan ini serupa dengan yang terpahat pada Candi Prambanan. Seperti yang banyak diceritakan, cerita Ramayana yang terpahat di candi Hindu tercantik mirip dengan cerita dalam tradisi lisan di India. Jalan cerita yang panjang dan menegangkan itu dirangkum dalam empat lakon atau babak, penculikan Sinta, misi Anoman ke Alengka, kematian Kumbakarna atau Rahwana, dan pertemuan kembali Rama-Sinta.",
        "Sebanyak 1200-an dari penjuru nusantara bisa dinikmati jika berkunjung Museum Sonobudoyo. Mulai dari keris Yogyakarta, Solo, Madura, hingga keris Kalimantan atau Mandau dan keris Sulawesi. Mengunjungi Museum Sonobudoyo adalah salah satu alternatif bila ingin melihat beragam koleksi keris dari penjuru nusantara dan benda-benda yang berkaitan dengannya. Museum yang menyimpan sekitar 1200-an koleksi keris (sebagian besar merupakan sumbangan Java Institut) ini akan mengobati kekecewaan anda, sebab Kraton Yogyakarta yang menyimpan keris-keris pusaka hingga kini tak memperbolehkan pengunjung menikmati koleksinya. Museum Sonobudoyo dapat dijangkau dengan mudah dari Kraton Yogyakarta, berada di seberang Alun Alun Utara Yogyakarta. Untuk memasukinya, anda hanya perlu membayar tiket seharga Rp 3.000,00. Sementara, untuk melihat beragam koleksi keris, prosedurnya cukup sulit karena mesti meminta ijin pada pimpinan museum. Hal itu disebabkan karena banyak koleksi keris masih disimpan di ruang koleksi, belum ditampilkan untuk umum.",
        "Wayang kulit adalah seni pertunjukan yang telah berusia lebih dari setengah milenium. Kemunculannya memiliki cerita tersendiri, terkait dengan masuknya Islam Jawa. Salah satu anggota Wali Songo menciptakannya dengan mengadopsi Wayang Beber yang berkembang pada masa kejayaan Hindu-Budha. Adopsi itu dilakukan karena wayang terlanjur lekat dengan orang Jawa sehingga menjadi media yang tepat untuk dakwah menyebarkan Islam, sementara agama Islam melarang bentuk seni rupa. Alhasil, diciptakan wayang kulit dimana orang hanya bisa melihat bayangan. Pagelaran wayang kulit dimainkan oleh seorang yang kiranya bisa disebut penghibur publik terhebat di dunia. Bagaimana tidak, selama semalam suntuk, sang dalang memainkan seluruh karakter aktor wayang kulit yang merupakan orang-orangan berbahan kulit kerbau dengan dihias motif hasil kerajinan tatah sungging (ukir kulit). Ia harus mengubah karakter suara, berganti intonasi, mengeluarkan guyonan dan bahkan menyanyi. Untuk menghidupkan suasana, dalang dibantu oleh musisi yang memainkan gamelan dan para sinden yang menyanyikan lagu-lagu Jawa. Tokoh-tokoh dalam wayang keseluruhannya berjumlah ratusan. Orang-orangan yang sedang tak dimainkan diletakkan dalam batang pisang yang ada di dekat sang dalang. Saat dimainkan, orang-orangan akan tampak sebagai bayangan di layar putih yang ada di depan sang dalang. Bayangan itu bisa tercipta karena setiap pertunjukan wayang memakai lampu minyak sebagai pencahayaan yang membantu pemantulan orang-orangan yang sedang dimainkan.",
        "Pantai Drini menjadi salah satu pantai istimewa di pesisir Gunungkidul karena sebuah pulau kecil di tengahnya, membagi pantai menjadi dua bagian. Konon di pulau tersebut banyak ditumbuhi santigi (Pemphis acidula), atau masyarakat di sini biasa menyebutnya drini. Itulah kenapa pantai dan pulau ini diberi nama drini. Bila laut sedang surut, kita bisa pergi ke pulau. Tak perlu menjadi climber untuk memanjat karang, karena tangga beton rela dipijak demi mengantar kita ke atas. Dari sini, pandangan kita bisa menyisir seluruh Pantai Drini, melihat gunungan alang-alang atap gazebo hingga deretan perahu nelayan. Semua tampak mungil, seperti miniatur bikinan kurcaci. Kini, tak ada lagi pohon drini, yang ada hanyalah pandan laut (Pandanus tectorius) memenuhi setiap jengkal tanah, berebut hidup dengan rerumputan.",
        "Di pantai paling terkenal di Kulon Progo ini kita bisa memancing, bersepeda, menaiki cano di laguna, bermotorcross ria, hingga sekedar duduk santai menikmati tetrapod yang berjuang memecah ombak sambil menunggu sunset tiba. Pemecah ombak dan laguna, dua kata itu langsung terlintas ketika mendengar nama Pantai Glagah. Keduanya seperti menunjukkan dua sisi berbeda dari pantai berpasir hitam ini. Ratusan tetrapod yang berjajar di sisi barat tanpa ampun memecah ombak Laut Selatan yang terkenal garang.",
        "Terletak di sebelah timur Pantai Sundak, pantai yang dibatasi bukit karang ini merupakan salah satu pantai yang menyajikan pemandangan berbeda dibandingkan pantai-pantai lain yang ada di Gunungkidul. Tidak hanya berhiaskan pasir putih, bukit karang, dan air biru jernih yang seolah memanggil-manggil wisatawan untuk menceburkan diri ke dalamnya, Pantai Indrayanti juga dilengkapi restoran dan cafe serta deretan penginapan yang akan memanjakan wisatawan. Beragam menu mulai dari hidangan laut hingga nasi goreng bisa di pesan di restoran yang menghadap ke pantai ini. Pada malam hari, gazebo-gazebo yang ada di bibir pantai akan terlihat cantik karena diterangi kerlip sinar lampu. Menikmati makan malam di cafe ini ditemani desau angin dan alunan debur ombak akan menjadi pengalaman romantis yang tak terlupa.",
        "Pantai Jogan menempati posisi istimewa karena keberadaan air terjun yang langsung jatuh dari atas tebing ke bibir laut, mengingatkan pada McWay Beach Waterfall di California. Selama ini, tak banyak pelancong yang tahu tentang Pantai Jogan. Lokasinya yang persis berada di sebelah barat Pantai Siung sering terlupa oleh para pemanjat yang dipacu semangat memeluk moleknya tebing Siung. Untuk mencapai Pantai Jogan, perlu waktu sekitar dua jam berkendara dari Jogja. Menyusuri jalanan aspal mulus, berkelok-kelok membelah perbukitan karst yang merupakan sisa lautan jutaan tahun silam. Bila kita sampai di Pos Retribusi Pantai Siung, artinya Pantai Jogan sudah dekat, karena sekitar 400 meter dari pos tersebut, akan terlihat papan kayu penunjuk arah menuju Jogan. Menggantikan aspal mulus, jalan setapak menjadi pemandu selanjutnya, mengantar Anda dengan didampingi dua sungai kecil di sisi kiri yang nantinya akan menyatu lalu menjelma menjadi air terjun.",
        "Tak seperti deretan pantai-pantai berpasir putih di Gunungkidul lainnya, Pantai Kesirat mempesona dengan karakternya sebagai pantai bertipe tebing karang. Tak ada pasir putih atau pemandangan buih ombak yang menepi di pantai ini. Hanya suara-suara deburan ombak yang pecah menabrak sisi-sisi karang. Garis pantai Kesirat yang langsung jatuh ke laut lepas dan jenis ikannya yang beragam adalah penyebab pantai ini populer di kalangan penggemar rock fishing.",
        "Pantai Krakal sudah lama kondang sebagai salah satu pantai di ujung selatan Jogja yang memiliki keindahan luar biasa. Garis pantainya landai dan ditaburi pasir putih dengan hempasan ombak yang jernih. Batu karang menghiasi sebagian besar bibir pantai, menjadi rumah bagi ikan-ikan karang berwarna-warni. Ikan damselfish kuning dengan aksen biru di punggungnya, ikan kepe-kepe (butterflyfish) bergaris-garis biru tua dan biru muda, serta sekelompok ikan kecil berwarna biru terang berenang di antara bebatuan. Kaki-kaki bintang laut hitam menjulur keluar dari balik batu tempat persembunyian mereka.",
        "Dasar laut Pantai Nglambor bagai akuarium semesta yang menyimpan sejuta pesona. Atas jasa sepasang \"kura-kura raksasa yang mampu menjinakkan garangnya ombak dari Samudera Hindia, panorama bawah laut di pesisir selatan ini pun bisa diselami keindahannya. Tak seperti pantai-pantai di sisi utara Jawa yang lebih ramah, tepian daratan yang langsung menyapa luasnya Samudera Hindia ini bukan tempat sesuai untuk menikmati asyiknya berenang di air asin atau serunya snorkeling menyaksikan keindahan panorama bawah laut bersama ikan-ikan kecil. Hingga kita terpaksa harus puas bermain air di pinggiran, di tempat buih-buih lautan mulai menghilang.",
        "Pantai Ngobaran ternyata kaya pesona budaya; mulai dari pura, masjid yang menghadap ke selatan, hingga potensi kuliner terpendam yaitu landak laut goreng. Ngobaran merupakan pantai yang cukup eksotik. Kalau air surut, anda bisa melihat hamparan alga (rumput laut) baik yang berwarna hijau maupun coklat. Jika dilihat dari atas, hamparan alga yang tumbuh di sela-sela karang tampak seperti sawah di wilayah padat penduduk. Puluhan jenis binatang laut juga terdapat di sela-sela karang, mulai dari landak laut, bintang laut, hingga golongan kerang-kerangan.",
        "Terletak di desa Kanigoro Kecamatan Saptosari kurang lebih 30 km di sebelah selatan kota Wonosari. Suatu pantai berupa teluk yang dikelilingi hamparan perbukitan kapur dan memiliki panorama yang sangat memukau dengan deburan ombak menerpa pasir putih. Para wisatawan dapat menyaksikan aktivitas kegiatan nelayan dan menikmati ikan siap saji atau membawa ikan segar sebagai oleh-oleh. Di Pantai Ngrenehan para wisatawan dapat menyaksikan aktivitas kegiatan nelayan dan menikmati ikan siap saji atau membawa ikan segar sebagai oleh-oleh.",
        "Pantai Parangtritis terletak 27 km selatan Kota Jogja dan mudah dicapai dengan transportasi umum yang beroperasi hingga pk 17.00 maupun kendaraan pribadi. Sore menjelang matahari terbenam adalah saat terbaik untuk mengunjungi pantai paling terkenal di Yogyakarta ini. Namun bila Anda tiba lebih cepat, tak ada salahnya untuk naik ke Tebing Gembirawati di belakang pantai ini. Dari sana kita bisa melihat seluruh area Pantai Parangtritis, laut selatan, hingga ke batas cakrawala. Pantai Parangtritis sangat lekat dengan mitos Ratu Kidul. Banyak orang Jawa percaya bahwa Pantai Parangtritis adalah gerbang kerajaan gaib Ratu Kidul. Hotel Queen of the South adalah sebuah resort yang diberi nama sesuai legenda ini.",
        "Pesona Pantai Pok Tunggal dengan hamparan pasir putih yang dikelilingi oleh dinding perbukitan merupakan lokasi yang asyik untuk dieksplorasi. Pantai Pok Tunggal yang terletak di antara Pantai Indrayanti dan Pantai Siung ini semakin mengukuhkan Gunungkidul sebagai gudangnya pantai-pantai cantik berpasir putih yang masih alami. Perjalanan ke Pantai Pok Tunggal memang tak terduga. Awalnya disuguhi jalan yang sulit, ternyata berujung pada surga tersembunyi yang memikat hati dan menantang nyali. Sebatang pohon yang ikonik membuat pantai ini makin cantik.",
        "Gazebo dan tempat makan menyambut saat mulai masuk ke area Pantai Slili. Jika dibandingkan pantai lain, Pantai Slili menjadi salah satu pantai yang memiliki garis pantai yang pendek. Pasir pantai yang putih bersih menambah keindahan dari pantai yang bersebelahan dengan Pantai Sadranan ini. Pantai ini cukup sepi, cocok bagi pengunjung yang ingin bersantai. Bebatuan karang yang ada di pinggir pantai dengan ombak-ombak kecil yang saling beradu, juga cocok untuk pengunjung yang ingin bermain-main air. Pantai ini juga cocok untuk menikmati indahnya sunrise dan sunset.",
        "Wediombo terletak di Desa Jepitu, Kecamatan Girisubo, Kabupaten Gunung Kidul. Pantai ini sangat mudah dijangkau bila sebelumnya telah datang ke Pantai Siung. Cukup kembali ke pertigaan di Tepus sebelum menuju ke Siung, kemudian belok kanan mengikuti alur jalan hingga menemukan papan petunjuk belok ke kanan untuk menuju Wediombo. Letak pantai ini jauh lebih ke bawah dibanding daratan sekitarnya. Beberapa puluh anak tangga mesti dituruni dulu sebelum dapat menjangkau pantai dan menikmati keelokan panoramanya. Sambil turun, di kanan kiri dapat dilihat beberapa ladang penduduk setempat, rumah-rumah tinggal dan vegetasi mangrove yang masih tersisa. Lalu lalang penduduk yang membawa rerumputan atau merawat ternak di kandang juga bisa dijumpai.",
        "Kabupaten Gunungkidul sudah lama terkenal dengan puluhan pantainya yang menarik hati. Terbentang dari perbatasan dengan Kabupaten Bantul di sebelah barat dan Provinsi Jawa Tengah di sebelah timur, ada 100-an pantai yang siap mewadahi keinginan kita melepas penat dari hilir mudik kota dengan bermain air laut, memancing, memandang senja atau sunrise, sampai berkemah. Nah, salah satu pantai yang cocok untuk kegiatan terakhir ini adalah pantai mini Wohkudu yang terletak di Gunungkidul sebelah barat. Inilah pantai yang menawarkan banyak alasan untuk mendirikan tenda di lahan-lahan kemahnya yang dilindungi oleh tebing-tebing.",
        "Pantai Siung kaya akan karang-karang raksasa. Tebing karangnya memiliki 250 jalur pemanjatan, juga tempat tepat untuk menikmati panorama pantai. Ada pula karang menyerupai siung wanara yang menjadi dasar penamaan pantai. Pantai Siung terletak di sebuah wilayah terpencil di Kabupaten Gunung Kidul, tepatnya sebelah selatan kecamatan Tepus. Jaraknya sekitar 70 km dari pusat kota Yogyakarta, atau sekitar 2 jam perjalanan. Menjangkau pantai ini dengan sepeda motor atau mobil menjadi pilihan banyak orang, sebab memang sulit menemukan angkutan umum. Colt atau bis dari kota Wonosari biasanya hanya sampai ke wilayah Tepus, itupun mesti menunggu berjam-jam.",
        "Candi Prambanan dibangun pada abad ke-9. Menjulang setinggi 47 meter dengan ornamen yang mengagumkan, kecantikan candi Hindu ini tak tertandingi. Candi Prambanan terletak 17 km ke arah timur dari pusat Kota Jogja dan bisa dijangkau dengan bus Trans Jogja. Sebagai salah satu warisan paling spektakuler dari abad ke-8 Masehi, Prambanan menjadi ikon wisata yang tidak pernah sepi dikunjungi wisatawan. Kemegahan arsitekturnya menjadi lambang kemajuan peradaban Mataram Kuno, salah satu kerajaan terbesar yang pernah berdiri di bumi Nusantara. Meskipun bentuknya tidak selengkap dulu, candi ini masih menarik hati ribuan orang yang datang dari seantero dunia dan berlomba-lomba mengabadikannya dalam bidikan lensa kamera",
        "Candi Borobudur adalah candi Buddha terbesar di dunia. Dibangun pada abad ke-9, Candi Borobudur sekarang menjadi magnet yang mampu menarik jutaan wisatawan setiap tahun. Temukan fakta menarik, sejarah, dan gambar Candi Borobudur di sini. Candi Borobudur memuat 2672 panel relief yang jika disusun berjajar maka panjangnya mencapai 6 km. Relief Candi Borobudur terbagi menjadi 4 kisah utama, yaitu: Karmawibangga, Lalitawistara, Jataka/Awadana, serta Gandawyuha. Selain mengisahkan tentang perjalanan hidup Sang Buddha dan ajarannya, relief Candi Borobudur juga merekam kemajuan masyarakat Jawa pada masa itu.",
        "Candi Mendut merupakan Candi Buddha yang dibangun oleh Raja Indra dari Wangsa Syailendra. Relung Candi Mendut menjadi singgasana untuk arca Buddha berukuran besar. Salah satu sisa kemegahan masa lalu adalah Candi Mendut yang terletak sekitar 3 km arah timur dari Candi Borobudur. Prasasti Kayumwungan yang ditemukan di Karangtengah menyebutkan bahwa Candi Mendut dibangun oleh Raja Indra dari Dinasti Syailendra. Candi berbentuk persegi empat dengan atap bertingkat yang dihiasi stupa-stupa kecil ini dibangun lebih dulu daripada Candi Pawon dan Candi Borobudur yang terletak dalam satu garis lurus. Berbeda dengan Candi Borobudur yang menghadap ke arah matahari terbit, maka pintu masuk Candi Mendut menghadap ke arah barat.",
        "Candi Ratu Boko adalah kompleks istana megah yang dibangun pada abad ke-8. Bangunan yang bisa dikatakan termegah di jamannya itu dibangun oleh salah satu kerabat pendiri Borobudur. Istana Ratu Boko adalah sebuah bangunan megah yang dibangun pada masa pemerintahan Rakai Panangkaran, salah satu keturunan Wangsa Syailendra. Istana yang awalnya bernama Abhayagiri Vihara (berarti biara di bukit yang penuh kedamaian) ini didirikan untuk tempat menyepi dan memfokuskan diri pada kehidupan spiritual. Berada di istana ini, anda bisa merasakan kedamaian sekaligus melihat pemandangan kota Yogyakarta dan Candi Prambanan dengan latar Gunung Merapi.",
        "Candi Ijo adalah candi yang letaknya paling tinggi di Yogyakarta yang menyuguhkan pesona alam dan budaya serta pesawat yang tengah landing. Candi inilah yang membuat landasan Bandara Adisutjipto tak bisa diperpanjang ke arah timur.Candi Ijo dibangun sekitar abad ke-9, di sebuah bukit yang dikenal dengan Bukit Hijau atau Gumuk Ijo yang ketinggiannya sekitar 410 m di atas permukaan laut. Karena ketinggiannya, maka bukan saja bangunan candi yang bisa dinikmati tetapi juga pemandangan alam di bawahnya berupa teras-teras seperti di daerah pertanian dengan kemiringan yang curam. Meski bukan daerah yang subur, pemandangan alam di sekitar candi sangat indah untuk dinikmati.",
        "Candi Plaosan yang dibangun Rakai Pikatan memiliki beberapa keunikan dibanding candi lain, yaitu dua candi utamanya yang \"kembar\" serta teras yang permukaannya halus. Di candi ini juga terdapat figur Vajrapani, Amitbha, dan Prajnaparamitha.Kompleks Plaosan dibagi menjadi 2 kelompok, yaitu Candi Plaosan Lor dan Candi Plaosan Kidul. Kedua candi itu memiliki teras berbentuk segi empat yang dikelilingi oleh dinding, tempat semedi berbentuk gardu di bagian barat serta stupa di sisi lainnya. Karena kesamaan itu, maka kenampakan Candi Plaosan Lor dan Kidul hampir serupa jika dilihat dari jauh sehingga sampai sekarang Candi Plaosan juga sering disebut candi kembar.",
        "Candi Kalasan adalah candi yang dipersembahkan untuk Dewi Tara yang dinding luarnya dilapisi semen kuno. Candi Budha tertua di Yogyakarta ini dibangun oleh Rakai Panangkaran, raja dari dinasti Syailendra yang juga mengkonsep pendirian Borobudur. Selesai dibangun pada tahun 778 M, Candi Tara menjadi candi Budha tertua di Yogyakarta. Candi yang berdiri tak jauh dari Jalan Yogya Solo ini dibangun sebagai penghargaan atas perkawinan Pancapana dari Dinasti Sanjaya dengan Dyah Pramudya Wardhani dari Dinasti Syailendra. Selain sebagai hadiah perkawinan, candi itu juga merupakan tanggapan usulan para raja untuk membangun satu lagi bangunan suci bagi Dewi Tara dan biara bagi para pendeta.",
        "Selesai dibangun pada tahun 778 M, Candi Tara menjadi candi Budha tertua di Yogyakarta. Candi yang berdiri tak jauh dari Jalan Yogya Solo ini dibangun sebagai penghargaan atas perkawinan Pancapana dari Dinasti Sanjaya dengan Dyah Pramudya Wardhani dari Dinasti Syailendra. Selain sebagai hadiah perkawinan, candi itu juga merupakan tanggapan usulan para raja untuk membangun satu lagi bangunan suci bagi Dewi Tara dan biara bagi para pendeta. Candi Pawon merupakan candi yang terletak tepat di sumbu garis yang menghubungkan Candi Mendut dan Candi Borobudur. Candi yang berbentuk persegi empat dengan atap bertingkat dan sebuah bilik di dalamnya ini berukuran jauh lebih kecil dibandingkan dengan Candi Mendut. Letak Candi Pawon cukup tersembunyi, dikelilingi rumah penduduk. Tersusun dari batuan vulkanik dengan perpaduan gaya bangunan Hindu Jawa kuno dan India, serta kemiripan corak ragam hias dengan Candi Mendut dan Candi Borobudur, para ahli sepakat bahwa ketiga candi ini dibangun pada abad yang sama. Hal ini dipertegas dengan Prasasti Kayumwungan atau Prasasti Karangtengah yang bertanggal 26 Mei 824 Masehi.",
        "Setelah terkubur selama ratusan tahun, bongkahan pertama ditemukan pada tahun 1966. Memerlukan waktu 21 tahun untuk menggali dan merangkai ratusan keping \"puzzle\" dari batu itu sebelum akhirnya Candi Sambisari berhasil direkonstruksi. Tak ada perasaan aneh yang menghinggapi Karyowinangun pada sebuah pagi di tahun 1966. Tapi sebuah kejadian langka dialaminya di sawah kala itu, ketika sedang mengayunkan cangkulnya ke tanah. Cangkul yang diayunkan ke tanah membentur sebuah batu besar yang setelah dilihat memiliki pahatan pada permukaannya. Karyowinangun dan warga sekitar pun merasa heran dengan keberadaan bongkahan batu itu.",
        "Candi Sari adalah candi Buddha yang dibangun pada abad VIII oleh Rakai Panangkaran, dan ditujukan sebagai biara bagi biksu-biksu yang bekerja di Candi Tara, 200 meter arah utara Candi Sari. Latar belakang pembangunannya terpahat dalam prasasti Kalasan yang menyebutkan perintah para penasehat keagamaan Kerajaan Mataram pada raja untuk mendirikan candi pemujaan bagi Dewi Tara dan biara untuk biksu yang akan bekerja di sana. Sebab prasasti ini bertahun 778 CE, bisa disimpulkan bahwa bersama Candi Kalasan, candi yang terdiri dari pondasi, tubuh, dan atap ini merupakan bangunan Budha tertua di Yogyakarta. Selain tertua, menarik pula bahwa candi ini mencerminkan kerukunan umat beragama masyarakat Hindu-Budha pada saat itu. Terbukti, Raja Mataram Kuno II yang beragama Hindu bersedia membuat dua bangunan megah sebagai fasilitas keagamaan rakyatnya yang beragama Buddha.",
        "Menurut sejarah, candi yang diperkirakan dibangun antara abad ke-9 dan 10 ini sebenarnya bernama Candi Suragedug. Namun, hiasan kala (sosok raksasa menyeramkan yang biasanya menghias gerbang atau pintu masuk candi) berbentuk barong di tiap sisi bangunan candi yang begitu khas membuat masyarakat sekitar lebih senang menjulukinya Candi Barong. Kala-kala barong di candi ini dalam mitologi Hindu dipercaya sebagai makhluk penjaga kesucian bangunan. Alih-alih menyeramkan seperti kala pada bangunan lainnya, barong-barong ini malah terkesan memberikan senyumannya. Selain barong, ornamen unik lain yang menghias candi ini adalah Ghana, si raksasa kerdil yang menopang relung candi. Berbeda dengan candi-candi lain di sekitarnya yang memiliki bilik (ruangan dalam candi), Candi Barong dibangun tanpa ada bilik di dalamnya, hanya ada relung yang dulunya berfungsi untuk meletakkan arca.",
        "Satu lagi candi yang ditemukan di Yogyakarta pada tahun 2009. Candi ini berada di halaman perpustakaan pusat UII. Bentuknya minimalis namun tak banyak mengalami kerusakan dan sangat rinci konstruksinya. Namanya adalah Candi Kimpulan. Nama ini disesuaikan dengan nama lokasi penemuannya yaitu di Dusun Kimpulan, Desa Umbulmartani, Ngemplak, Sleman karena belum ditemukan prasasti di dekat candi.Candi Kimpulan memiliki bentuk yang minimalis. Di tepinya terdapat pagar batu terbuat dari batu gundul (boulder) membentuk sebuah bidang persegi yang direkatkan dengan tanah liat. Untuk melihat candi lebih dekat, kami harus melompati batu-batuan ini. Menuju ke tengah, terhampar dua candi yang berupa lantai tinggi. Candi yang menghadap ke timur dan berbentuk persegi merupakan candi induk. Beberapa ornamen ditemukan di dinding candi ini, berupa kala berpola antefiks, relief orang duduk memegang tangkai teratai, dan roset (teratai dan mutiara). Di dalam candinya terdapat lingga-yoni, wadah gerabah, arca Ganesha, dan umpak batu. Peripih dan wadah perunggu yang berasal dari dalam lubang yoni, bawah lantai, dan bawah umpak juga ditemukan di candi yang lebar pintu hanya 60 sentimeter."
    )
    private val seniImage = intArrayOf(
        R.drawable.jazz,
        R.drawable.keraton,
        R.drawable.jemparingan,
        R.drawable.affandi,
        R.drawable.ramayana,
        R.drawable.sonobudoyo,
        R.drawable.wayang,
        R.drawable.pantai_drini,
        R.drawable.pantai_glagah,
        R.drawable.pantai_indrayanti,
        R.drawable.pantai_jogan,
        R.drawable.pantai_kesirat,
        R.drawable.pantai_krakal,
        R.drawable.pantai_nglambor,
        R.drawable.pantai_ngobaran,
        R.drawable.pantai_ngrenehan,
        R.drawable.pantai_parangtritis,
        R.drawable.pantai_pok_tunggal,
        R.drawable.pantai_slili,
        R.drawable.pantai_wediombo,
        R.drawable.pantai_wohkudu,
        R.drawable.pantaisiung,
        R.drawable.candi_prambanan,
        R.drawable.candi_borobudur,
        R.drawable.candi_mendut,
        R.drawable.ratu_boko,
        R.drawable.candi_ijo,
        R.drawable.candi_plaosan,
        R.drawable.candi_kalasan,
        R.drawable.candi_pawon,
        R.drawable.candi_sambisari,
        R.drawable.candi_sari,
        R.drawable.candi_barong,
        R.drawable.candi_kimpulan
    )

    val listData: ArrayList<Seni>
        get() {
            val list = arrayListOf<Seni>()
            for (position in seniNames.indices){
                val seni = Seni()
                seni.name = seniNames[position]
                seni.detail = seniDetails[position]
                seni.photo = seniImage[position]
                list.add(seni)
            }
            return list
        }

}